### ISSUE TITLE
Endpoint "Table of Contents" showing all webhooks as TEST ONLY

### ISSUE THREAD

**Issue by dianahansen** [raymondberg/btray#1]
I had a few different types of webhooks roll through this evening (subscription created, subscription charged successfully), but they're all listed as TEST ONLY in the Table of Contents on the Webhook Endpoint detail page:
<img width="278" alt="screen shot 2016-02-08 at 5 47 02 pm" src="https://cloud.githubusercontent.com/assets/16963599/12903374/dc408aca-ce8c-11e5-91da-c9474e472873.png">

Not sure if they're supposed to be listed by type, but that could be helpful for finding activity. It also might make sense to call the "Table of Contents" something like "Webhook History" or "Webhook Activity"?

**Comment by raymondberg** [comment]
This is an overhang of the version 0.x work I did. I'm going to see what I can do about storing that extra data about each webhook kind in the database.

**Comment by raymondberg** [comment]
@dhansenBT This should be taken care of with the last two commits. Please note that this will only apply to future webhooks, anything currently in the production app will show up as `unknown`.

Add kinds: 2afbbe63edcc30a01eafbe2d23bb24b6cda0d836
Reformat: f814f5b275f90a9decceef7676f18d30fae30b15

Reformat includes reversing the order for ease of use.
